bengaluru House data

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"D:\DSA\pythonForML\stats\Bengaluru_House_Data.csv")

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
data.shape

(13320, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
for columns in data.columns:
    print(data[columns].value_counts())
    print("*"*50)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
**************************************************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
**************************************************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
**************************************************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
**************************************************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
**************************************************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
**************************************************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
**************************************************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
**************************************************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
**************************************************

In [7]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
data.drop(columns=["area_type","society","balcony","availability"],inplace=True)

In [9]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [11]:
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [12]:
data['location']=data['location'].fillna('Sarjapur Road')

In [13]:
data['location'].isna().sum()

0

In [14]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [15]:
data['size']=data['size'].fillna('2 BHK')

In [16]:
data['size'].isna().sum()

0

In [17]:
data['bath'].median()

2.0

In [18]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [20]:
data['bhk']=data['size'].str.split(' ').str.get(0).astype(int)

In [21]:
data.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [22]:
data[data['bhk']>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [23]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [24]:
def convertRange(x):
    temp=x.split('-')
    if len(temp)==2:
        return(float(temp[0])+float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [25]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [26]:
data['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [27]:
data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [28]:
data.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [29]:
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Uvce Layout                         1
Abshot Layout                       1
Name: count, Length: 1306, dtype: int64

In [30]:
data['location']=data['location'].apply(lambda x: x.strip())

In [31]:
data['location'].value_counts()

location
Whitefield                            541
Sarjapur  Road                        399
Electronic City                       304
Kanakpura Road                        273
Thanisandra                           237
                                     ...
1Channasandra                           1
Hosahalli                               1
Vijayabank bank layout                  1
near Ramanashree California resort      1
Abshot Layout                           1
Name: count, Length: 1295, dtype: int64

In [34]:
location_count=data['location'].value_counts()

In [35]:
location_count_less_10=location_count[location_count<=10]

In [36]:
location_count_less_10

location
BTM 1st Stage                         10
Nagadevanahalli                       10
Basapura                              10
Sector 1 HSR Layout                   10
Dairy Circle                          10
                                      ..
1Channasandra                          1
Hosahalli                              1
Vijayabank bank layout                 1
near Ramanashree California resort     1
Abshot Layout                          1
Name: count, Length: 1054, dtype: int64

In [37]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [39]:
data['location'].value_counts()

location
other                 2886
Whitefield             541
Sarjapur  Road         399
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

In [40]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [42]:
data['total_sqft_per_bhk']=data['total_sqft']/data['bhk']

In [43]:
data['total_sqft_per_bhk'].describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
Name: total_sqft_per_bhk, dtype: float64

In [44]:
data['price_per_sqft'].describe()

count    1.327400e+04
mean     7.907501e+03
std      1.064296e+05
min      2.678298e+02
25%      4.266865e+03
50%      5.434306e+03
75%      7.311746e+03
max      1.200000e+07
Name: price_per_sqft, dtype: float64

In [49]:
def remove_outliers(data):
    df_output=pd.DataFrame()
    for key,subdf in data.groupby('location'):
        m=np.mean(subdf['price_per_sqft'])
        st=np.std(subdf['price_per_sqft'])
        reduced_df=subdf[(subdf['price_per_sqft']>(m-st)) & (subdf['price_per_sqft']<=(m+st))]
        df_output=pd.concat([df_output,reduced_df],ignore_index=True)
    return df_output

In [47]:
m=np.mean([2,3,4,5,6,7,8,9,10])
n=np.std([2,3,4,5,6,7,8,9,10])

In [48]:
m,n

(6.0, 2.581988897471611)

In [61]:
data=remove_outliers(data)

In [62]:
data['location'].describe()

count      5718
unique      242
top       other
freq       1083
Name: location, dtype: object

In [52]:
data.describe()

,total_sqft,bath,price,bhk,price_per_sqft,total_sqft_per_bhk
count,11488.000000,11488.000000,11488.000000,11488.000000,11488.000000,11488.000000
mean,1537.976810,2.605066,105.238232,2.719185,6303.086658,576.125551
std,1145.700742,1.208022,138.520527,1.152969,3636.502296,290.163859
min,250.000000,1.000000,8.000000,1.000000,267.829813,66.666667
25%,1100.000000,2.000000,50.000000,2.000000,4285.714286,481.666667
50%,1280.000000,2.000000,70.000000,3.000000,5311.170467,555.611111
75%,1660.000000,3.000000,110.000000,3.000000,6849.601172,625.000000
max,52272.000000,27.000000,3600.000000,27.000000,53150.000000,17424.000000

In [57]:
def bhk_outliers(data):
    exclude_indices=np.array([])
    for location,location_df in data.groupby('location'):
        bhk_stats={}
        for bhk,bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk]={
                'mean':np.mean(bhk_df['price_per_sqft']),
                'std':np.std(bhk_df['price_per_sqft']),
                'count':bhk_df.shape[0]
            }
        # print(location,bhk, bhk_stats[bhk])
        for bhk,bhk_df in location_df.groupby('bhk'):
                stats=bhk_stats.get(bhk-1)
                if stats and stats['count']>5:
                    exclude_indices=np.append(exclude_indices,bhk_df[bhk_df['price_per_sqft']<(stats['mean'])].index.values)
    return data.drop(exclude_indices,axis='index')

In [56]:
data=bhk_outliers(data)

1st Block Jayanagar 8 {'mean': 14857.142857142857, 'std': 0.0, 'count': 1}
1st Phase JP Nagar 5 {'mean': 5666.666666666667, 'std': 0.0, 'count': 1}
2nd Phase Judicial Layout 3 {'mean': 3620.93991671624, 'std': 241.87983343248052, 'count': 5}
2nd Stage Nagarbhavi 6 {'mean': 16438.88888888889, 'std': 1646.9013178139373, 'count': 3}
5th Block Hbr Layout 6 {'mean': 5882.35294117647, 'std': 0.0, 'count': 1}
5th Phase JP Nagar 7 {'mean': 3800.0, 'std': 0.0, 'count': 1}
6th Phase JP Nagar 8 {'mean': 8181.818181818182, 'std': 0.0, 'count': 1}
7th Phase JP Nagar 6 {'mean': 8858.267716535433, 'std': 0.0, 'count': 1}
8th Phase JP Nagar 5 {'mean': 4335.260115606937, 'std': 0.0, 'count': 1}
9th Phase JP Nagar 4 {'mean': 6145.488721804511, 'std': 1562.8334117678646, 'count': 4}
AECS Layout 3 {'mean': 4500.0, 'std': 0.0, 'count': 1}
Abbigere 8 {'mean': 5000.0, 'std': 0.0, 'count': 1}
Akshaya Nagar 4 {'mean': 6944.444444444444, 'std': 0.0, 'count': 1}
Ambalipura 4 {'mean': 5503.386809269163, 'std': 339.75044563279835, 'count': 2}
Ambedkar Nagar 4 {'mean': 7684.086312870249, 'std': 531.2111375546801, 'count': 2}
Amruthahalli 3 {'mean': 5574.846418310635, 'std': 1077.4444900329127, 'count': 7}
Anandapura 4 {'mean': 5145.797598627787, 'std': 0.0, 'count': 1}
Ananth Nagar 3 {'mean': 3239.9055148973916, 'std': 333.6052126335633, 'count': 3}
Anekal 4 {'mean': 3000.0, 'std': 0.0, 'count': 1}
Anjanapura 4 {'mean': 3852.102102102102, 'std': 796.5465465465463, 'count': 2}
Ardendale 4 {'mean': 6445.687085352693, 'std': 663.0498079730814, 'count': 7}
Arekere 4 {'mean': 5239.852398523985, 'std': 0.0, 'count': 1}
Attibele 4 {'mean': 3840.959409594096, 'std': 540.9594095940961, 'count': 2}
BEML Layout 5 {'mean': 9375.0, 'std': 0.0, 'count': 1}
BTM 2nd Stage 5 {'mean': 13913.04347826087, 'std': 0.0, 'count': 1}
BTM Layout 6 {'mean': 5000.0, 'std': 0.0, 'count': 1}
Babusapalaya 3 {'mean': 3669.941030877054, 'std': 601.932707346431, 'count': 10}
Badavala Nagar 3 {'mean': 6279.828480978357, 'std': 42.27887875035828, 'count': 7}
Balagere 2 {'mean': 6191.495143186286, 'std': 543.3822583816924, 'count': 28}
Banashankari 4 {'mean': 3800.0, 'std': 0.0, 'count': 1}
Banashankari Stage II 5 {'mean': 18214.285714285714, 'std': 3035.7142857142853, 'count': 2}
Banashankari Stage III 9 {'mean': 12820.51282051282, 'std': 0.0, 'count': 1}
Banashankari Stage V 3 {'mean': 3581.57134026118, 'std': 544.8260330690271, 'count': 9}
Banashankari Stage VI 4 {'mean': 5662.878787878788, 'std': 2264.874902876769, 'count': 3}
Banaswadi 5 {'mean': 9011.735855666491, 'std': 1654.9308110001748, 'count': 2}
Banjara Layout 5 {'mean': 8000.0, 'std': 0.0, 'count': 1}
Bannerghatta 4 {'mean': 6420.068783616955, 'std': 1444.7505345143272, 'count': 3}
Bannerghatta Road 6 {'mean': 8108.108108108108, 'std': 0.0, 'count': 1}
Basavangudi 4 {'mean': 10547.90052996331, 'std': 3564.966038035845, 'count': 4}
Basaveshwara Nagar 7 {'mean': 14227.642276422765, 'std': 0.0, 'count': 1}
Battarahalli 3 {'mean': 5015.40017552159, 'std': 337.7428143761158, 'count': 8}
Begur 4 {'mean': 3906.25, 'std': 0.0, 'count': 1}
Begur Road 4 {'mean': 4908.181698669715, 'std': 101.64150578232626, 'count': 3}
Bellandur 4 {'mean': 6759.122130530177, 'std': 845.9579630611066, 'count': 4}
Benson Town 4 {'mean': 14856.497304850036, 'std': 282.5062734599014, 'count': 2}
Bharathi Nagar 3 {'mean': 4200.120192307692, 'std': 0.0, 'count': 1}
Bhoganhalli 4 {'mean': 5777.756745789307, 'std': 871.3161320532748, 'count': 11}
Billekahalli 3 {'mean': 6179.829109009818, 'std': 1029.8742088847782, 'count': 6}
Binny Pete 4 {'mean': 8382.135462880804, 'std': 1141.674060928719, 'count': 2}
Bisuvanahalli 3 {'mean': 4024.56125276605, 'std': 471.4028570072472, 'count': 32}
Bommanahalli 8 {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}
Bommasandra 3 {'mean': 3958.5886460970883, 'std': 611.2144535922934, 'count': 12}
Bommasandra Industrial Area 3 {'mean': 2863.160206574431, 'std': 59.9654742104211, 'count': 7}
Bommenahalli 4 {'mean': 8564.836466843257, 'std': 717.6221010374835, 'count': 6}
Brookefield 5 {'mean': 8974.358974358975, 'std': 0.0, 'count': 1}
Budigere 3 {'mean': 4995.782145950289, 'std': 304.7321376982579, 'count': 22}
CV Raman Nagar 5 {'mean': 8333.333333333334, 'std': 0.0, 'count': 1}
Chamrajpet 6 {'mean': 15333.333333333334, 'std': 0.0, 'count': 1}
Chandapura 4 {'mean': 3498.942358540455, 'std': 0.0, 'count': 1}
Channasandra 6 {'mean': 4285.714285714285, 'std': 0.0, 'count': 1}
Chikka Tirupathi 4 {'mean': 4568.837506464278, 'std': 449.90860011916783, 'count': 7}
Chikkabanavar 8 {'mean': 2750.0, 'std': 0.0, 'count': 1}
Chikkalasandra 3 {'mean': 4209.541795721919, 'std': 468.54274526277595, 'count': 14}
Choodasandra 4 {'mean': 8645.533141210375, 'std': 0.0, 'count': 1}
Cooke Town 4 {'mean': 11016.71535215839, 'std': 375.6897111327489, 'count': 2}
Cox Town 3 {'mean': 7780.757079649942, 'std': 1186.6163940265649, 'count': 4}
Cunningham Road 4 {'mean': 22399.47110781565, 'std': 2068.0898222124456, 'count': 3}
Dasanapura 3 {'mean': 5032.659409020218, 'std': 255.05443234836684, 'count': 2}
Dasarahalli 3 {'mean': 5324.248120300752, 'std': 390.03759398496277, 'count': 2}
Devanahalli 5 {'mean': 4166.666666666667, 'std': 0.0, 'count': 1}
Devarachikkanahalli 8 {'mean': 6296.2962962962965, 'std': 0.0, 'count': 1}
Dodda Nekkundi 3 {'mean': 5934.221068512782, 'std': 1020.763160342317, 'count': 7}
Doddaballapur 4 {'mean': 7306.716419287801, 'std': 1508.6011290881638, 'count': 4}
Doddakallasandra 3 {'mean': 3999.4695049973843, 'std': 0.3068175498332698, 'count': 4}
Doddathoguru 3 {'mean': 3920.463690699665, 'std': 643.1324346449559, 'count': 7}
Domlur 3 {'mean': 8601.445470741792, 'std': 2229.698831405483, 'count': 14}
Dommasandra 4 {'mean': 2518.5185185185187, 'std': 0.0, 'count': 1}
EPIP Zone 4 {'mean': 6621.198451923327, 'std': 53.43624500234158, 'count': 3}
Electronic City 4 {'mean': 5201.660222644956, 'std': 931.5912756321039, 'count': 5}
Electronic City Phase II 4 {'mean': 4680.190258840645, 'std': 272.972080657902, 'count': 5}
Electronics City Phase 1 3 {'mean': 4851.575882244288, 'std': 533.2869033255906, 'count': 20}
Frazer Town 4 {'mean': 9580.08324073647, 'std': 1086.7606066839614, 'count': 6}
GM Palaya 3 {'mean': 4628.867942650349, 'std': 354.0596141419346, 'count': 6}
Garudachar Palya 3 {'mean': 4580.959776242796, 'std': 23.67431495380781, 'count': 6}
Giri Nagar 6 {'mean': 15104.166666666668, 'std': 1727.4087449767712, 'count': 4}
Gollarapalya Hosahalli 4 {'mean': 4514.435695538058, 'std': 0.0, 'count': 1}
Gottigere 4 {'mean': 4433.333333333333, 'std': 286.74417556808754, 'count': 3}
Green Glen Layout 4 {'mean': 6835.898556082042, 'std': 333.3960060843011, 'count': 4}
Gubbalala 5 {'mean': 5486.381322957199, 'std': 0.0, 'count': 1}
Gunjur 4 {'mean': 4750.0, 'std': 0.0, 'count': 1}
HAL 2nd Stage 8 {'mean': 26000.0, 'std': 0.0, 'count': 1}
HBR Layout 4 {'mean': 10414.351851851852, 'std': 1745.258310087662, 'count': 4}
HRBR Layout 4 {'mean': 12225.877192982456, 'std': 4337.159929697198, 'count': 4}
HSR Layout 5 {'mean': 7916.666666666666, 'std': 2083.3333333333335, 'count': 2}
Haralur Road 4 {'mean': 6235.082567660682, 'std': 921.4968176715216, 'count': 8}
Harlur 4 {'mean': 6806.220763959648, 'std': 749.5046631700119, 'count': 6}
Hebbal 4 {'mean': 8100.068735136814, 'std': 948.3635171057358, 'count': 25}
Hebbal Kempapura 5 {'mean': 8320.802005012532, 'std': 373.56532189325577, 'count': 3}
Hegde Nagar 6 {'mean': 7000.0, 'std': 0.0, 'count': 1}
Hennur 5 {'mean': 5000.0, 'std': 0.0, 'count': 1}
Hennur Road 8 {'mean': 5000.0, 'std': 0.0, 'count': 1}
Hoodi 5 {'mean': 6666.666666666667, 'std': 0.0, 'count': 1}
Horamavu Agara 5 {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}
Horamavu Banaswadi 6 {'mean': 5263.1578947368425, 'std': 0.0, 'count': 1}
Hormavu 4 {'mean': 4186.386210926088, 'std': 853.0528775927548, 'count': 2}
Hosa Road 5 {'mean': 6111.111111111111, 'std': 0.0, 'count': 1}
Hosakerehalli 9 {'mean': 10869.565217391304, 'std': 0.0, 'count': 1}
Hoskote 3 {'mean': 3600.5359456638253, 'std': 751.6624895989767, 'count': 8}
Hosur Road 5 {'mean': 6136.363636363636, 'std': 1136.3636363636365, 'count': 2}
Hulimavu 5 {'mean': 8416.666666666666, 'std': 0.0, 'count': 1}
ISRO Layout 6 {'mean': 5681.818181818182, 'std': 0.0, 'count': 1}
ITPL 4 {'mean': 5293.33921482135, 'std': 0.0, 'count': 1}
Iblur Village 5 {'mean': 7753.573598412542, 'std': 47.31793204808173, 'count': 2}
Indira Nagar 8 {'mean': 18461.53846153846, 'std': 0.0, 'count': 1}
JP Nagar 7 {'mean': 5925.925925925926, 'std': 0.0, 'count': 1}
Jakkur 4 {'mean': 7290.394789156389, 'std': 914.7687249133417, 'count': 5}
Jalahalli 4 {'mean': 7500.0, 'std': 0.0, 'count': 1}
Jalahalli East 4 {'mean': 6666.666666666667, 'std': 0.0, 'count': 2}
Jigani 4 {'mean': 6253.529974684973, 'std': 1001.9905300468881, 'count': 2}
Judicial Layout 7 {'mean': 16583.333333333332, 'std': 0.0, 'count': 1}
KR Puram 9 {'mean': 4347.826086956522, 'std': 0.0, 'count': 1}
Kadubeesanahalli 3 {'mean': 5422.047214586422, 'std': 1213.899445999799, 'count': 5}
Kadugodi 4 {'mean': 5033.333333333334, 'std': 566.6666666666665, 'count': 2}
Kaggadasapura 4 {'mean': 4390.180878552972, 'std': 194.09107967146167, 'count': 3}
Kaggalipura 3 {'mean': 5067.840459935322, 'std': 267.71813441909836, 'count': 5}
Kaikondrahalli 6 {'mean': 6654.835847382431, 'std': 0.0, 'count': 1}
Kalena Agrahara 3 {'mean': 5540.391844954946, 'std': 782.6421967834364, 'count': 8}
Kalyan nagar 4 {'mean': 7043.982789343301, 'std': 850.7540527619626, 'count': 2}
Kambipura 3 {'mean': 4613.88537985688, 'std': 442.39294983399617, 'count': 7}
Kammanahalli 6 {'mean': 10869.565217391304, 'std': 0.0, 'count': 1}
Kammasandra 3 {'mean': 3237.2655812105695, 'std': 861.3497493389445, 'count': 7}
Kanakapura 4 {'mean': 5633.802816901409, 'std': 0.0, 'count': 1}
Kanakpura Road 5 {'mean': 6018.518518518518, 'std': 0.0, 'count': 1}
Kannamangala 4 {'mean': 5885.74639875218, 'std': 555.9126968865866, 'count': 3}
Karuna Nagar 3 {'mean': 7548.041260232853, 'std': 960.2983417649926, 'count': 6}
Kasavanhalli 4 {'mean': 7188.150786398397, 'std': 888.4937505820675, 'count': 6}
Kasturi Nagar 4 {'mean': 6387.757738248516, 'std': 205.06926597089296, 'count': 2}
Kathriguppe 3 {'mean': 5791.147903867095, 'std': 283.97304755177413, 'count': 18}
Kaval Byrasandra 3 {'mean': 5339.504172308165, 'std': 1412.8791899774815, 'count': 4}
Kenchenahalli 3 {'mean': 5460.627817637033, 'std': 264.58222613843435, 'count': 3}
Kengeri 8 {'mean': 4333.333333333333, 'std': 0.0, 'count': 1}
Kengeri Satellite Town 5 {'mean': 5833.333333333333, 'std': 0.0, 'count': 1}
Kereguddadahalli 3 {'mean': 3203.254608294931, 'std': 173.2774907327058, 'count': 5}
Kodichikkanahalli 5 {'mean': 4753.086419753086, 'std': 174.5942669596414, 'count': 3}
Kodigehaali 3 {'mean': 5932.628698743195, 'std': 1418.7220163805841, 'count': 4}
Kodigehalli 4 {'mean': 14166.666666666666, 'std': 0.0, 'count': 1}
Kodihalli 4 {'mean': 10893.922389045523, 'std': 716.3686036821398, 'count': 3}
Kogilu 8 {'mean': 8750.0, 'std': 0.0, 'count': 1}
Konanakunte 9 {'mean': 9433.962264150943, 'std': 0.0, 'count': 1}
Koramangala 4 {'mean': 12567.348894001134, 'std': 1286.9271971129865, 'count': 5}
Kothannur 4 {'mean': 3781.25, 'std': 968.75, 'count': 2}
Kothanur 8 {'mean': 7619.047619047619, 'std': 0.0, 'count': 1}
Kudlu 4 {'mean': 5428.571428571428, 'std': 0.0, 'count': 1}
Kudlu Gate 4 {'mean': 5324.675324675325, 'std': 0.0, 'count': 1}
Kumaraswami Layout 7 {'mean': 8120.915032679738, 'std': 3554.264313725769, 'count': 3}
Kundalahalli 4 {'mean': 8365.231318918251, 'std': 1028.8263996833173, 'count': 3}
LB Shastri Nagar 3 {'mean': 4888.392857142857, 'std': 825.8928571428573, 'count': 2}
Laggere 8 {'mean': 6111.111111111111, 'std': 0.0, 'count': 1}
Lakshminarayana Pura 3 {'mean': 6841.666666666666, 'std': 91.66666666666652, 'count': 2}
Lingadheeranahalli 4 {'mean': 6948.373789156925, 'std': 137.69782791285036, 'count': 3}
Magadi Road 6 {'mean': 3916.6666666666665, 'std': 0.0, 'count': 1}
Mahadevpura 3 {'mean': 4870.419072507448, 'std': 464.96928202282703, 'count': 9}
Mahalakshmi Layout 8 {'mean': 16740.08810572687, 'std': 0.0, 'count': 1}
Mallasandra 3 {'mean': 5557.259722141612, 'std': 756.1882822123313, 'count': 5}
Malleshpalya 3 {'mean': 4425.035578878555, 'std': 860.0436344837372, 'count': 4}
Malleshwaram 7 {'mean': 18333.333333333332, 'std': 0.0, 'count': 1}
Marathahalli 4 {'mean': 6160.540698577994, 'std': 807.182049168838, 'count': 20}
Margondanahalli 3 {'mean': 5057.999244463333, 'std': 256.1953829260381, 'count': 3}
Marsur 4 {'mean': 8055.555555555556, 'std': 0.0, 'count': 1}
Mico Layout 9 {'mean': 4200.0, 'std': 0.0, 'count': 1}
Munnekollal 10 {'mean': 2777.777777777778, 'std': 0.0, 'count': 1}
Murugeshpalya 3 {'mean': 4894.704240288178, 'std': 1069.0984472302289, 'count': 8}
Mysore Road 3 {'mean': 5619.037394414652, 'std': 1426.3169779168866, 'count': 18}
NGR Layout 2 {'mean': 4489.826297505917, 'std': 29.998439759192205, 'count': 8}
NRI Layout 5 {'mean': 5200.0, 'std': 0.0, 'count': 1}
Nagarbhavi 5 {'mean': 7200.0, 'std': 0.0, 'count': 1}
Nagasandra 8 {'mean': 4000.0, 'std': 0.0, 'count': 1}
Nagavara 4 {'mean': 5265.610902466384, 'std': 257.5980819535639, 'count': 2}
Nagavarapalya 3 {'mean': 6153.846153846154, 'std': 0.0, 'count': 1}
Narayanapura 3 {'mean': 5624.607559361702, 'std': 176.28469731669043, 'count': 4}
Neeladri Nagar 10 {'mean': 4000.0, 'std': 0.0, 'count': 1}
Nehru Nagar 4 {'mean': 4994.3116788028365, 'std': 83.97863012649077, 'count': 2}
OMBR Layout 5 {'mean': 11458.333333333334, 'std': 0.0, 'count': 1}
Old Airport Road 4 {'mean': 7400.652269436282, 'std': 366.65275351747255, 'count': 19}
Old Madras Road 5 {'mean': 6125.232403718459, 'std': 408.1009296148736, 'count': 2}
Padmanabhanagar 4 {'mean': 6176.470588235294, 'std': 0.0, 'count': 1}
Pai Layout 6 {'mean': 4605.263157894737, 'std': 0.0, 'count': 1}
Panathur 3 {'mean': 5824.381873424201, 'std': 756.1120640080887, 'count': 5}
Parappana Agrahara 2 {'mean': 3894.570971024669, 'std': 52.57420919375578, 'count': 14}
Pattandur Agrahara 3 {'mean': 5161.290322580645, 'std': 0.0, 'count': 2}
Poorna Pragna Layout 3 {'mean': 4049.309690274269, 'std': 111.94750610317409, 'count': 12}
Prithvi Layout 4 {'mean': 7988.165680473373, 'std': 0.0, 'count': 1}
R.T. Nagar 9 {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}
Rachenahalli 4 {'mean': 6015.859994531036, 'std': 0.0, 'count': 1}
Raja Rajeshwari Nagar 9 {'mean': 6666.666666666667, 'std': 0.0, 'count': 1}
Rajaji Nagar 8 {'mean': 15000.0, 'std': 0.0, 'count': 1}
Rajiv Nagar 4 {'mean': 6315.890833058215, 'std': 707.5762737250174, 'count': 6}
Ramagondanahalli 4 {'mean': 6714.753447126966, 'std': 1179.0391614126816, 'count': 2}
Ramamurthy Nagar 9 {'mean': 7500.0, 'std': 0.0, 'count': 1}
Rayasandra 5 {'mean': 4722.222222222223, 'std': 694.4444444444446, 'count': 2}
Sahakara Nagar 4 {'mean': 8574.597565763643, 'std': 1660.1577347813115, 'count': 3}
Sanjay nagar 5 {'mean': 7575.757575757576, 'std': 0.0, 'count': 1}
Sarakki Nagar 4 {'mean': 11118.213921641485, 'std': 58.695321233468675, 'count': 3}
Sarjapur 4 {'mean': 4798.6758762009795, 'std': 982.6102032032919, 'count': 11}
Sarjapur  Road 5 {'mean': 7761.975371209643, 'std': 2136.8725137333695, 'count': 9}
Sarjapura - Attibele Road 3 {'mean': 3677.009046693256, 'std': 568.4897414332066, 'count': 7}
Sector 2 HSR Layout 3 {'mean': 5960.40202845711, 'std': 1667.8563593678139, 'count': 6}
Sector 7 HSR Layout 5 {'mean': 10000.0, 'std': 0.0, 'count': 1}
Seegehalli 4 {'mean': 5000.0, 'std': 0.0, 'count': 2}
Shampura 6 {'mean': 6521.739130434783, 'std': 0.0, 'count': 1}
Shivaji Nagar 3 {'mean': 5529.173836286845, 'std': 635.2097253569909, 'count': 2}
Singasandra 4 {'mean': 4156.25634887236, 'std': 652.1768364106035, 'count': 3}
Somasundara Palya 4 {'mean': 5833.333333333333, 'std': 0.0, 'count': 1}
Sompura 4 {'mean': 3953.4883720930234, 'std': 0.0, 'count': 1}
Sonnenahalli 3 {'mean': 4706.376756380032, 'std': 441.79167132471156, 'count': 5}
Subramanyapura 3 {'mean': 5295.724008100502, 'std': 737.1336358433358, 'count': 16}
Sultan Palaya 6 {'mean': 9722.222222222223, 'std': 0.0, 'count': 1}
TC Palaya 6 {'mean': 6900.0, 'std': 0.0, 'count': 1}
Talaghattapura 3 {'mean': 6525.3392336488205, 'std': 694.1463657221601, 'count': 22}
Thanisandra 6 {'mean': 4571.428571428572, 'std': 0.0, 'count': 1}
Thigalarapalya 4 {'mean': 7478.280524334292, 'std': 267.3908548713968, 'count': 11}
Thubarahalli 4 {'mean': 6289.473684210527, 'std': 0.0, 'count': 1}
Thyagaraja Nagar 5 {'mean': 14035.087719298246, 'std': 0.0, 'count': 1}
Tindlu 7 {'mean': 5333.333333333333, 'std': 0.0, 'count': 1}
Tumkur Road 4 {'mean': 5454.545454545455, 'std': 0.0, 'count': 1}
Ulsoor 9 {'mean': 9130.434782608696, 'std': 0.0, 'count': 1}
Uttarahalli 6 {'mean': 6396.825396825397, 'std': 2202.570419420666, 'count': 3}
Varthur 5 {'mean': 6500.0, 'std': 0.0, 'count': 1}
Varthur Road 3 {'mean': 3800.411985861906, 'std': 850.7508048357686, 'count': 2}
Vasanthapura 3 {'mean': 4285.714285714285, 'std': 0.0, 'count': 1}
Vidyaranyapura 9 {'mean': 8333.333333333334, 'std': 0.0, 'count': 1}
Vijayanagar 8 {'mean': 12000.0, 'std': 0.0, 'count': 1}
Vishveshwarya Layout 7 {'mean': 5625.0, 'std': 0.0, 'count': 1}
Vishwapriya Layout 5 {'mean': 4642.857142857143, 'std': 0.0, 'count': 1}
Vittasandra 3 {'mean': 5113.14174326139, 'std': 100.56430016629145, 'count': 7}
Whitefield 6 {'mean': 13500.0, 'std': 0.0, 'count': 1}
Yelachenahalli 5 {'mean': 9476.03121516165, 'std': 0.0, 'count': 1}
Yelahanka 6 {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}
Yelahanka New Town 4 {'mean': 5202.863961813842, 'std': 0.0, 'count': 1}
Yelenahalli 3 {'mean': 3918.9457070707067, 'std': 143.76151982471873, 'count': 3}
Yeshwanthpur 6 {'mean': 7400.0, 'std': 0.0, 'count': 1}
other 27 {'mean': 2875.0, 'std': 0.0, 'count': 1}

In [58]:
data=bhk_outliers(data)

In [59]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft,total_sqft_per_bhk
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860,712.500000
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491,543.333333
2,1st Block Jayanagar,6 BHK,1200.0,6.0,125.0,6,10416.666667,200.000000
3,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333,625.000000
4,1st Block Jayanagar,7 Bedroom,930.0,4.0,85.0,7,9139.784946,132.857143
...,...,...,...,...,...,...,...,...
11479,other,7 Bedroom,1400.0,7.0,218.0,7,15571.428571,200.000000
11482,other,2 BHK,1353.0,2.0,110.0,2,8130.081301,676.500000
11483,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443,812.000000
11486,other,4 Bedroom,1200.0,5.0,325.0,4,27083.333333,300.000000
11487,other,4 BHK,3600.0,5.0,400.0,4,11111.111111,900.000000

In [60]:
data.shape

(8039, 8)

In [66]:
data.drop(['size','price_per_sqft','total_sqft_per_bhk'],axis='columns',inplace=True)

In [67]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      1630.0   3.0  194.0    3
1  1st Block Jayanagar      1875.0   2.0  235.0    3
2  1st Block Jayanagar      1200.0   2.0  130.0    3
3  1st Block Jayanagar      1235.0   2.0  148.0    2
4   1st Phase JP Nagar      1875.0   3.0  167.0    3

In [68]:
data.to_csv(r"D:\DSA\pythonForML\stats\Bengaluru_House_Data_Cleaned.csv",index=False)

In [ ]:
# X=data.iloc[:,0:-1]wrong

In [73]:
X=data.drop(['price'],axis='columns')
y=data['price']

In [74]:
X

                 location  total_sqft  bath  bhk
0     1st Block Jayanagar      1630.0   3.0    3
1     1st Block Jayanagar      1875.0   2.0    3
2     1st Block Jayanagar      1200.0   2.0    3
3     1st Block Jayanagar      1235.0   2.0    2
4      1st Phase JP Nagar      1875.0   3.0    3
...                   ...         ...   ...  ...
5713                other      1800.0   1.0    1
5714                other      1140.0   1.0    2
5715                other      1400.0   7.0    7
5716                other      1353.0   2.0    2
5717                other      3600.0   5.0    4

[5718 rows x 4 columns]

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [77]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [79]:
print(X_train.shape)
print(X_test.shape)

(4574, 4)
(1144, 4)

In [80]:
column_trans=make_column_transformer((OneHotEncoder(), ['location']), remainder='passthrough')

In [82]:
scaler=StandardScaler()

In [87]:
column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), ['location']),
    (StandardScaler(), ['total_sqft', 'bath', 'bhk']),
    remainder='drop'   # or passthrough if needed
)

pipe = make_pipeline(column_trans, LinearRegression())

pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('linearregression', LinearRegression())])

In [88]:
y_pred_lr=pipe.predict(X_test)

In [89]:
r2_score(y_test,y_pred_lr)

0.8401189747905238

lasso

In [91]:
lasso=Lasso()

In [94]:
pipe=make_pipeline(column_trans,lasso)

In [95]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('lasso', Lasso())])

In [96]:
y_pred_lasso=pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.7191824745601634

Ridge

In [97]:
pipe=make_pipeline(column_trans,Ridge())

In [98]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('ridge', Ridge())])

In [99]:
y_pred_ridge=pipe.predict(X_test)

In [100]:
r2_score(y_test,y_pred_ridge)

0.8416738356913646

In [101]:
print("R2 Score for Linear Regression:", r2_score(y_test,y_pred_lr))
print("R2 Score for Lasso Regression:", r2_score(y_test,y_pred_lasso))
print("R2 Score for Ridge Regression:", r2_score(y_test,y_pred_ridge))

R2 Score for Linear Regression: 0.8401189747905238
R2 Score for Lasso Regression: 0.7191824745601634
R2 Score for Ridge Regression: 0.8416738356913646

In [103]:
import pickle

In [104]:
pickle.dump(pipe,open('Bengaluru_House_Price_Prediction_Model.pkl','wb'))